### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by shrx** [NeverSinkGaming/NeverSink-Filter#1]
> `INGAME: Escape -> Options -> UI -> Scroll down -> Select NeverSink.filter`

Where exactly do I select the filter in the UI options menu?

**Comment by Exportforce** [comment]
ESC -> Options -> UI -> Bottom

But those instructions are already in the filter, if you'd read it.

**Comment by shrx** [comment]
Turned out the filter was in incorrect folder, so the option wasn't available,

**Comment by Exportforce** [comment]
And because YOU make a mistake, you downvote other peoples help, what an assmove.

**Comment by shrx** [comment]
How exactly did you help? You just copied the same line that I mentioned.

**Comment by NeverSinkGaming** [comment]
Chill guys, I'm glad this is solved, no need to make a fuss over it.
Thanks for helping Exportforce. It's nice to see other users helping out fellow exiles.
