### ISSUE TITLE
Trash uniques vs T1 Uniques and Exalted Orbs - same sound

### ISSUE THREAD

**Issue by nesro** [NeverSinkGaming/NeverSink-Filter#3]
Hi,
I didn't investigate if the sound is "absolutely" different, but it just sound the same. There should be a specific and unique sound for things you always pick up (Exalteds Orbs, T1 uniques), just like for Sorceress Boots.

I started to see this as a serious problem with my prolif pizza that is burning monsters to death 1-2 screens away from me. It's just a waste of time going back and see a trash unique.

Thank you,
Tomas

**Comment by NeverSinkGaming** [comment]
Thanks for the feedback, but this is not something I agree to. 

There are 5 reasons for it:

1) it's impossible to classify every single item. There are special cases such as jewels, where it's impossible to evaluate if the item is good or bad ( unid items of the same base can not be distinguished by the filter ).

2) it's exciting to find out what dropped offscreen, it's about detection, not trivializing something that happens rarely - unique dropping in a direction you wouldn't move to anyway

3) I want to use a sound set people are used to. Using a new sound for an ultra rare item is dangerous.

4) the filter would become much more dependent on instant updates in case of patches and economy fluctuations. 

5) personal preference and statistical distribution of those who want it. ( you're the minority based on my experience ).

**Comment by nesro** [comment]
Thank you for your response. I appreciate it. I will adjust the filter for my needs next league. Let me just react to your reasons:

1) I don't want to start a discussion here, because I understand that this is very subjective preference. I just think this is possible and I will tweak your filter to my needs next league. I just want to know when a T1, T2 uniques, 6Ls, exalteds, divines, mirrors, T12+ maps drops and I want to never miss it, and there is not too much of these items.

2) I understand that it could be exciting. But this isn't working with the clear speed meta. I finished the 1200 Voll challenge and if the run takes 20-30 seconds, you really notice every backtracking. That's the main purpose of lootfilter sound alert: back-track only if something valuable is on the ground.

3) I agree. I don't know if it's possible to play multiple sounds since I didn't learn all the possibilities yet, but I want to just add another sound to what I want. I'd feel that I didn't broke anything and still get what I wanted.

4) I agree. There are some auto-updating lootfilters already. But I understand that's too much work and it's time consuming for so little benefit.

5) I really never cared what others think about this. But I believe too.

I hope it didn't sound harsh. I really love the style of your loot-filter. You're doing amazing  job here. Thank you! :)

**Comment by NeverSinkGaming** [comment]
All your arguments are quite good, but in the end it's a distribution question of what the majority (also me) prefer. However, for the next version (likely PoE 2.4 / Filter 4.0), I'm planning to upload it on a website that will allow you to customize settings in your filter version (using a simple GUI) before downloading (or simply download presets). 

For now you'll have to update yourself :).

Thank you for your input. I'll consider them.

NeverSink
