### ISSUE TITLE
"BaseType rule: No base types found matching x" error

### ISSUE THREAD

**Issue by baartd** [NeverSinkGaming/NeverSink-Filter#4]
I get the error: Unable to parse parameter for BaseType rule: No base types found matching "Mountain Ledge"

Personal version: Line 402
Full version: Line 402
Magic find version: Line 403
Slick version: Line 394

screenshot of in game error : https://baartd.s-ul.eu/4vkU9JoJ

**Comment by baartd** [comment]
Started looking at the problem. Removing "Mountain Ledge" from the filter. Continue having problems. Finished deleting all the unparse able params. Filter loads corrrectly now. 

screenshot of in game errors: https://baartd.s-ul.eu/bYmYx16F

**Comment by NeverSinkGaming** [comment]
You're using an outdated version of the filter. (The new version doesn't use map names, it uses drop levels instead)

**Comment by NeverSinkGaming** [comment]
Simply redownload and use one of the 4 v4.0 versions from the main folder

**Comment by baartd** [comment]
Holy shit I'm so sorry! I feel so dumb right now.

**Comment by NeverSinkGaming** [comment]
All good, closed
