### ISSUE TITLE
Some items just display a black box

### ISSUE THREAD

**Issue by jabbedxorz** [NeverSinkGaming/NeverSink-Filter#7]
This started happening after the most recent patch. I've seen this happen with a few currency items like transmutes and blacksmiths and a lot of the essences.

The screenshot below has an example of a dusk blade. 
![screenshot-0001](https://cloud.githubusercontent.com/assets/22029038/18275188/43564be8-741c-11e6-8fca-dc7723b8b1f6.png)

**Comment by jabbedxorz** [comment]
Here's another example. There's a missing Cobalt Jewel, Viridian Jewel, and a Mage's Vestment.

![screenshot-0002](https://cloud.githubusercontent.com/assets/22029038/18276055/ce4dd09c-741f-11e6-9410-c5c2cd349281.png)

**Comment by codyst78** [comment]
Same problem here. Reverted back to 4.0

**Comment by NeverSinkGaming** [comment]
Same issue/explanation as in https://github.com/NeverSinkGaming/NeverSink-Filter/issues/7

Closed, please use the link above for discussion. The changes are by no means related to the 4.0/4.01 version differences by the way.
