### ISSUE TITLE
Item display a unknown language

### ISSUE THREAD

**Issue by phanton0152** [NeverSinkGaming/NeverSink-Filter#8]
![font bug](https://cloud.githubusercontent.com/assets/18247553/18281618/e718ef30-7433-11e6-9c2f-6451807d9306.png)

The picture speak for then self...

**Comment by NeverSinkGaming** [comment]
Same issue/explanation as: https://github.com/NeverSinkGaming/NeverSink-Filter/issues/7

Closed.
